### ISSUE TITLE
Error when sending file via client

### ISSUE THREAD

**Issue by physiii** [a-wing/filegogo#150]
I am able to transfer files via the webapp however when using client I get the following error:

$ go run ./main.go send -s http://192.168.1.10:3000/5451 /home/andy//Videos/20191006_142104.mp4
panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
filegogo/client.(*Client).overrideServer(0xc00000e798)
        /home/andy/code/filegogo/client/client.go:83 +0x251
filegogo/client.(*Client).Send(0xc00000e798, {0x1d, 0xc0000efcb0}, {0xc0001b9110, 0x1, 0x1})
        /home/andy/code/filegogo/client/client.go:104 +0x10e
filegogo/cmd.init.1.func2(0xc0001da0c0)
        /home/andy/code/filegogo/cmd/send.go:28 +0xed
github.com/urfave/cli/v2.(*Command).Run(0xc00018d560, 0xc000091f80)
        /home/andy/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0x1000440, {0xc4db10, 0xc000024110}, {0xc0000200a0, 0x5, 0x5})
        /home/andy/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
        /home/andy/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
filegogo/cmd.Execute()
        /home/andy/code/filegogo/cmd/cmd.go:43 +0x45
main.main()
        /home/andy/code/filegogo/main.go:6 +0x17

**Comment by a-wing** [comment]
For Deverloper, room server is default 8080

```bash
go run ./main.go send -s http://192.168.1.10:8080/5451 /home/andy//Videos/20191006_142104.mp4
```

<img width="1280" alt="Screen Shot 2022-03-26 at 21 54 54" src="https://user-images.githubusercontent.com/18189138/160242615-beccb634-9de4-4e64-b994-8bc3bf39bd34.png">
