### ISSUE TITLE
[Question] webrtc 如何避免或减少加密的开销, 因为wireguard会主导加密

### ISSUE THREAD

**Issue by shynome** [a-wing/filegogo#264]
我在做一个关于 wireguard over webrtc 的项目 [wgortc](https://github.com/shynome/wgortc), 其中遇到了性能问题:

|                   | 速度   | 区别                                                               |
| ----------------- | ------ | ------------------------------------------------------------------ |
| wiireguard-kernel | 800M/s | -                                                                  |
| wireguard-go      | 270M/s | -                                                                  |
| tailscale         | 600M/s | 仅使用了 ICE 来发现端口, 比 wg-go 快这么多, 应该是用了内核模块 |
| wgortc            | 55M/s  | webrtc 单 data channel, 换成["媒体通信"](https://webrtcforthecurious.com/zh/docs/06-media-communication/#rtp)会不会好点?                  |

谢谢你的查看

-----
更新: 修改 mtu 为 1120 (1200-80) 后速度由 40M/s 提升到了 55M/s (1200是webrtc默认选择的mtu)

**Comment by a-wing** [comment]
我想起三年前和别人在群里讨论的 dtls 速度的问题

<img width="343" alt="Screenshot 2023-06-30 at 11 51 01" src="https://github.com/a-wing/filegogo/assets/18189138/596d3bce-1343-44f5-bfdb-aed14b0b4b4d">

<img width="1869" alt="image_2020-12-05_15-55-33" src="https://github.com/a-wing/filegogo/assets/18189138/d518fe02-a846-49af-b910-4e1a773ea202">

看看火焰图，哪个那个函数慢的。

加密慢可能是没走 asm 的函数，调整编译参数试试。但速度也和具体的处理器有关

**Comment by shynome** [comment]
看来 wireguard over webrtc 不是速度要求型 vpn 的好选择, 感谢回复
